#!/usr/bin/env bash
# archives pictures which cannot create 16 unique colors with imagemagick

waldir=${HOME}/usr/pics/wallpapers
arcdir=${HOME}/usr/pics/wallpapers/archive

get_colors() {
	convert $1 +dither -colors 16 -unique-colors txt:- | grep -E -o " \#.{6}"
}

for w in ${waldir}/*.jpg; do
	colors=($(get_colors "${w}"))
	(( "${#colors[@]}" <= 15 )) && {
		echo "archiving $(basename ${w})"
		mv "${w}" "${arcdir}/"
	}
done
