#!/bin/sh

FILE=~/usr/docs/misc/presents_cleo_geburt

usage() {
    echo "Usage: $(basename $0) [haes]"
}

read_input() {
    while [ -z "$FROM" ]; do
        read -p "From? " FROM
    done
    while [ -z "$PRESENT" ]; do
        read -p "Present? " PRESENT
    done
}

add() {
    while [ -n $FROM -o -n $PRESENT ]; do
        read_input

        RESPONSE=N

        read -p "Is this correct? \"$FROM;$PRESENT\" (y/N) " RESPONSE
        case $RESPONSE in
            y|Y) break ;;
            n|N) unset FROM PRESENT ;;
            *) echo "Enter y or n" ;;
        esac
    done

    if [ -n "$FROM" ] && [ -n "$PRESENT" ]; then
        echo "$FROM;$PRESENT" >> $FILE
    else
        echo "Nothing added"
    fi
}

show() {
    column -s\; -t "$FILE"
}

edit() {
    vim $FILE
}

case $1 in
    s) show ;;
    a) add ;;
    e) edit ;;
    *) usage ;;
esac
