#!/bin/bash
# dependencies: xrandr, printf, sleep, lemonbar

width="110"
height="22"
font="misc ohsnap:size=7"
gaps="$(bspc query -T -m focused | jq .windowGap)"

resolution="$(xrandr --nograb --current | awk '/\*/ {printf $1; exit}')"
monitor_width="${resolution/x*}"

offset_right="$((monitor_width - width - "${gaps}" ))"
geometry_right="${width}x${height}+${offset_right}+$(( "${gaps}" / 2))"

offset_left="$(( "${gaps}" ))"
geometry_left="${width}x${height}+${offset_left}+$(( "${gaps}" / 2))"

bar-date(){
	printf "%(%d.%m  %I:%M)T\n"
}

bar-vol(){
	printf "%2d\n" "$(pamixer --get-volume)"
}

while :; do
	printf "%s\n" "%{c}$(bar-date)"
	sleep 30s
done |\

lemonbar -d -g "$geometry_right" -f "$font" -B "${1:-#f0f0f0}" -F "${2:-#000000}" -n "bar" &

while :; do
	printf "%s\n" "%{c}$(bar-vol)  $(bat)"
	sleep 1s
done |\

lemonbar -d -g "$geometry_left" -f "$font" -B "${1:-#f0f0f0}" -F "${2:-#000000}" -n "bar" &
