#!/bin/bash

MONWIDTH=$(wattr w `lsw -r`)

newmails() {
	ls "$MAIL/new" | wc -l
}

vol() {
	test "$(volume -s)" = "on" && volume || echo "!$(volume)"
}

# left bar
while :; do
	printf "%s%4s %3d %2d\n" "%{c}" "$(vol)" "$(bat)" "$(newmails)"
	sleep 1s
done |\

mybar $GAPS "bar" &

# right bar
while :; do
	printf "%s%(%d.%m  %I:%M)T\n" "%{c}"
	sleep 60s 
done |\

mybar $(( MONWIDTH - MONWIDTH / 15 - GAPS )) "bar" &
