#!/bin/bash

COLORS=(FF0000 FF4400 FF8800 FFCC00 FFFF00 CCFF00 88FF00 44FF00 00FF00)
FREQ=${FREQ:-0.05s}

getcol()
{
	STEP=$(( $(bat) / ${#COLORS[@]} ))
	echo ${COLORS[$STEP]}
}

while :; do
	chwb -c $(getcol) $(pfw)
	sleep $FREQ
done

