#!/bin/sh

shopt -s extglob

usage() {
    echo "Usage: $(basename $0) [+-ch] [num]"
}

which xbacklight > /dev/null 2>&1 \
    || ( echo "xbacklight not installed" && exit 1 )

case $1 in
    +) xbacklight -inc 10 & ;;
    -) xbacklight -dec 10 & ;;
    h) usage ;;
    +([[:digit:]]) ) xbacklight -set $1 & ;;
    *) printf "%2.0f\n" `xbacklight -get` ;;
esac
