#!/bin/bash

EMAIL="$(pass tu-darmstadt/ess/ess-bonusmail 2> /dev/null)"

usage() {
	cat << EOF
Usage: $(basename $0) <file>
	file: file to send
EOF
}

sendmail() {
	pass uni/ess-mail-text | mutt -s "[ESS] Bonusabgabe" -a $1 -- $EMAIL
	notify send
}

test $# -ne 1 && usage && exit 1
test -z $EMAIL && printf "No mail found\n" > /dev/stderr && exit 1
test ! -f $1 && printf "'%s' is no file\n" $1 > /dev/stderr && exit 1

read -n 1 -p "You are sure you want to send '$1' to '$EMAIL'? " RESPONSE

case $RESPONSE in
	[yY])		sendmail $1; printf "\n" ;;
	*)			printf "\n%s\n" "Abort." ;;
esac
