#!/bin/sh

unknown() {
	echo "Unknown device. Only [b]ose, [f]airphone, [r]evolve allowed."
	exit 1
}

usage() {
	echo "Usage: $(basename $0) [h] <b|f|r> <c|d>"
	exit 1
}

test $# -ne 2 && usage && exit 1

case $1 in
	h) usage ;;
	b) DEVICEID=2C:41:A1:09:48:75 ;;
	f) DEVICEID=00:00:AB:BD:B2:6B ;;
	r) DEVICEID=04:52:C7:FB:3A:3F ;;
	*) unknown ;;
esac

case $2 in
	c|1) bluetoothctl connect $DEVICEID ;;
	d|0) bluetoothctl disconnect $DEVICEID ;;
esac
