#!/bin//sh
# by z3bra

WALLDIR=$HOME/usr/pics/wallpapers

setwall() {
    FILE=$(readlink -f $1)
    hsetroot -fill $FILE
    ln -sf $FILE $HOME/.wall
    notify "changed bg to $(basename ${1%%.*})"
}

test -n "$1" && setwall $1 && exit

find $WALLDIR \( -iname *.jpg -o -iname *.png \) | meh -list | while read FILE; do
    setwall $FILE
done

