#!/bin/bash

PASS_STORE="$HOME/.password-store/"

for f in $(find $PASS_STORE -name "*.gpg")
do
    echo $SEPARATOR
    FILE=`echo $f | sed "s,^$PASS_STORE,,"`
    echo ${FILE%.*}
    pass show ${FILE%.*}
    SEPARATOR="##########"
done
