#!/usr/bin/python

import urllib.request

from bs4 import BeautifulSoup
from tabulate import tabulate

URL = 'https://soziales.hessen.de/gesundheit/corona-hessen/taegliche-uebersicht-der-bestaetigten-sars-cov-2-faelle'
TABLE_CLASS = 'hzd_responsive_tables-processed'

with urllib.request.urlopen(URL) as response:
    html = response.read()

soup = BeautifulSoup(html, 'html.parser')
table_class_tag = soup.find('table')

rows = [[ele.text.replace('.', '').replace(',', '.').lower() for ele in row.find_all('td')] for row in table_class_tag.find_all('tr')[2:]]
print(tabulate(rows, headers=['kreis', '1d#', '1drip#', '#', 'rip#', '7d#', '7di']))
