#!/bin/bash

usage() {
	cat << EOF
Usage: $(basename $0) <start> <end> <steps>
EOF
}

test $# -ne 3 && usage && exit 1

S=$1
E=$2
STEPS=$(( $3 / 2 ))

COLORS=( $(gcsq -n -s $STEPS $S $E) )
COLORS_REV=()

indices=( ${!COLORS[@]} )
rev_index=0

for ((i=${#indices[@]} - 1; i >= 0; i--)) ; do
    COLORS_REV[rev_index]="${COLORS[indices[i]]}"
		rev_index=$(( rev_index + 1 ))
done

echo "${COLORS[@]} ${COLORS_REV[@]}" 
