#!/bin/bash

usage() {
    echo "Usage: $(basename $0) <dir> <pattern> <name>"
}

test "$#" != "3" && usage && exit 1

cd "$1"

open "$(find * -iname "$2" -a -type f -o -type l | menu "-q -p $3")" > /dev/null 2>&1
