#!/bin/bash

usage() {
	printf "usage: $(basename $0) <dir>\n" > /dev/stderr
}

test $# -ne 1 && usage && exit 1
test ! -e $1 && usage && exit 1

FULLPATH="$(readlink -f $1)"

while [ -d $FULLPATH ]; do
	NEW="$(ls $FULLPATH | menu)"

	# if dmenu returns failure exit
	test -z "$NEW" && exit 1

	FULLPATH="$FULLPATH/$NEW"
done

xdg-open $FULLPATH &
