#!/bin/bash

usage() {
	echo "usage: $(basename $0) <dir>"
}

test $# -ne 1 && usage && exit 0
test ! -e $1 && usage && exit 0

FULLPATH="$(readlink -f $1)"

while [ -d $FULLPATH ]; do
	NEW="$(ls $FULLPATH | menu)"

	# if dmenu returns failure exit
	test -z "$NEW" && exit 0

	FULLPATH="$FULLPATH/$NEW"
done

xdg-open $FULLPATH &
