#!/bin/bash

source $COLOR_FILE

PAD='    '

newmails() {
    ls "$MAIL/new" | wc -l
}

volume() {
    if [ $(vol s) = "on" ]; then vol; else echo "!$(vol)"; fi
}

left() {
    printf "%4s%4d%3s\n" "$(vol)" "$(bat)" "$(newmails)"
}

mid() {
    printf "%s" "$(xtitle)"
}

right() {
    printf "%(%d.%m  %I:%M)T"
}

while :; do
    printf "%s%s%s\n" "%{l}$(left)" "%{c}$(mid)" "%{r}$(right)"
    sleep 1s
done |\

lemonbar -d -g "x14" -f "$BAR_FONT" -B "$fg" -F "$bg" -n "bar"
