#!/bin/sh
test -f $HOME/.$USER && cat $HOME/etc/r4ndom
echo ""
echo "                                             Hi [32mr4ndom[0m"
echo "                                  You have [33m`ls $MAIL/new | wc -l`[0m new mails"
#echo ""
#echo "                                Your events today are:"
#echo "                              $(khal list | sponge | sed "1d")"
