#!/bin/sh

UNI_DIR="/home/phil/usr/docs/uni"
PAPER_DIR="$UNI_DIR/paper"

DIRS="$(find "$UNI_DIR/msc_itsec" -iname "paper" -type d)"

cd "$PAPER_DIR"
for d in $DIRS; do
    for paper in $d/*.pdf; do
        printf "Linking: %s\n" "$paper"
        ln -sf "$paper" .
    done
done

find . -xtype l -delete
