#!/bin/bash
 
# Dependencies:
# ffmpeg
# i3lock-color-git

source ${HOME}/.cache/wal/colors.sh
 
IMAGE=/tmp/i3lock.png
LOCK=$HOME/.config/lockicon.png
RES=$(xrandr --current | grep '*' | uniq | awk '{print $1}')

if [[ $1 != "" ]]; then
    TEXT=$1
fi

ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "boxblur=20,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $IMAGE

i3lock --textcolor="${color4}ff" --insidecolor="${color0}1c" --ringcolor="${color4}aa" --linecolor=00000000 --keyhlcolor="${color1}ff" --ringvercolor=00ff0030 --insidevercolor=0000001c --ringwrongcolor=ff000030 --insidewrongcolor=0000001c  -i $IMAGE

rm $IMAGE
