#!/bin/sh

DIR=$HOME/var/nextcloud/misc/meetings
DATE=$(date '+%F')

test -n $1 && TITLE="$1"
while [ -z "$TITLE" ]; do
	read -p 'Meeting title: ' TITLE
done

TMP=$HOME/tmp/${DATE}_$TITLE.md
FINAL=$DIR/${DATE}_$TITLE.md

if [ ! -f $FINAL ]; then
	cat << EOF > $TMP
# ${TITLE}
Datum: ${DATE}
Protokoll: ${USER}

# TOPs
EOF

	vim $TMP
	mv $TMP $FINAL
else
	vim $FINAL
fi

