#!/bin/bash

resolution="$(xrandr --nograb --current | awk '/\*/ {printf $1; exit}')"

height="20"
gaps="10"

dmenu_run -p "run" -q -i -name "menu" -class "dmenu" -h "$height" -fn "misc ohsnap:size=7" -nb "#000000" -nf "#c2c2b0" -sb "#c2c2b0" -sf "#000000" 2>&1
