#!/bin/bash

source ~/.config/themes/current

resolution="$(xrandr --nograb --current | awk '/\*/ {printf $1; exit}')"

height="20"
gaps="10"

dmenu_run -p "run" -q -i -name "menu" -class "dmenu" -h "$height" -fn "misc ohsnap:size=7" -nb "$COLOR_BASE" -nf "$COLOR_GOLD" -sb "$COLOR_GOLD" -sf "$COLOR_BASE" 2>&1
