#!/bin/bash

MPDPID=$(pgrep mpd)
STATEFILE="$HOME/.config/mpd/state"

status() {
    status="$(mpc status | grep -o -e "playing\|paused")"

    case "$status" in
        playing) mpc current ;;
         paused) echo "paused" ;;
              *) echo "stopped" ;;
    esac
}

[ ! $MPDPID ] && printf "Error: mpd is not running\n" && exit 1

while :; do
    printf "  %s\n" "$(status)"
    sleep 1
done | WIDTH=650 mybar 190 "mpdbar"
