#!/bin/bash

MPDPID=$(pidof mpd)
STATEFILE="$HOME/.config/mpd/state"

usage() {
    echo "Usage: $(basename $0) [-h] [-d] [-nv]"
    [ $VERBOSE ] && cat <<EOF
    -h : print this help

    -d : run in daemon mode

    -n : notify using \`notify\`
    -v : be more verbose
EOF
    exit 1
}

out() {
    printf "MPD: %s\n" "$@"
    [ $NOTIFY ] && notify "MPD: $@"
}

out_status() {
    status="$(mpc status | grep -o -e "playing\|paused")"

    case "$status" in
        playing)
            [ $VERBOSE ] && printf "Currently playing:\n"
            out "$(mpc current)"
            ;;
        paused) 
            out "paused" 
            ;;
        *) 
            out "stopped"
            ;;
    esac
}

run_daemon() {
    [ $VERBOSE ] && printf "Starting mpdnotify in daemon mode.\n"
    while read -r; do
        out_status
    done < <(mpc idleloop player)
    [ $VERBOSE ] && printf "Stopped mpdnotify.\n"

}

[ ! $MPDPID ] && printf "Error: MPD is not running\n" && exit 1

while getopts "hdvn" opt; do
    case $opt in
        d) DAEMON=true ;;
        v) VERBOSE=true ;;
        n) NOTIFY=true ;;
        *) usage ;;
    esac
done

[ $DAEMON ] && run_daemon || out_status
