#!/bin/bash

MPDPID=$(pidof mpd)
STATEFILE="$HOME/.config/mpd/state"

usage() {
    cat << EOF
Usage: $(basename $0) [-d] [-n]
    -d : run in daemon mode
    -n : notify using \`notify\`
EOF
    exit 1
}

out() {
    [ $NOTIFY ] && notify "MPD: $(status)" || \
        [ $DAEMON ] && printf "%-$(tput cols)s\r" "$(status)" || \
        status
}

status() {
    status="$(mpc status | grep -o -e "playing\|paused")"

    case "$status" in
        playing) mpc current ;;
         paused) echo "paused" ;;
              *) echo "stopped" ;;
    esac
}

run_daemon() {
    while read -r; do
        out status
    done < <(mpc idleloop)

}

[ ! $MPDPID ] && printf "Error: MPD is not running\n" && exit 1

while getopts "dnh" opt; do
    case $opt in
        d) DAEMON=true ;;
        n) NOTIFY=true ;;
        *) usage ;;
    esac
done

[ $DAEMON ] && run_daemon || out status
