#!/bin/sh
# move new photos

PICS=~/usr/pics
NEW=$PICS/new
MOUNT_POINT=/mnt

mkdir -p $NEW

find "$MOUNT_POINT" \
    -type f \
    \( -name '*.JPG' -o -name '*.CR2' \) \
    -exec cp -a {} $NEW \;

# include fdupes
# fdupes -rqNA $PICS
