#!/usr/bin/python

import os
import shutil
import sys

from datetime import datetime
from os.path import basename, isfile, join, splitext


BASE_DIR=os.path.join(os.getenv('HOME'), 'usr', 'pics', 'photos')


def usage(program_name):
    print(f'Usage: {basename(program_name)} files ..')
    sys.exit(1)


def extract_date(path):
    try:
        filename, _ = splitext(basename(path))
        return datetime.strptime(filename, '%Y%m%d_%H%M%S')
    except:
        return


if not all(map(lambda f: isfile(f), sys.argv[1:])):
    usage(sys.argv[0])


for f in sys.argv[1:]:
    date = extract_date(f)

    if not date:
        continue

    destination_dir = join(BASE_DIR, f'{date.year}', f'{date.month:02d}')

    if not os.path.isdir(destination_dir):
        print(f'makedir {destination_dir}')
        os.makedirs(destination_dir)

    shutil.move(f, destination_dir)
