#!/bin/bash

usage() {
	cat << EOF
Usage: $(basename $0) <offset x> <name>
EOF
}

test $# -ne 2 && usage && exit 1

geometry="${WIDTH:-150}x20+${1:-10}+$(( 10 / 2))"
lemonbar -d -g "$geometry" -f "misc ohsnap:size=7" -B "#c2c2b0" -F "#000000" -n "$2"
