#!/bin/bash

source ~/.config/themes/current

usage() {
	cat << EOF
Usage: $(basename $0) <offset x> <name>
EOF
}

test $# -ne 2 && usage && exit 1

geometry="${WIDTH:-150}x20+${1}"
lemonbar -d -g "$geometry" -f "misc ohsnap:size=7" -B "$COLOR_BASE" -F "$COLOR_GOLD" -n "$2"
