#!/bin/bash

source $COLOR_FILE

usage() {
	cat << EOF
Usage: $(basename $0) <offset x> <name>
EOF
}

test $# -ne 2 && usage && exit 1

MON_WIDTH=$(wattr w `lsw -r`)
TMP_WIDTH="$(( MON_WIDTH / 15 ))"
width="${WIDTH:-$TMP_WIDTH}"

geometry="${width}x$TOP_PADDING+${1:-0}+$(( GAPS / 2))"

lemonbar -d -g "$geometry" -f "$BAR_FONT" -B "$fg" -F "$bg" -n "$2"
