#!/usr/bin/env bash
# sends first arg as notification

test $# -eq 0 && exit 1

SLEEP=${SLEEP:-10s}

MON_WIDTH=$(wattr w `lsw -r`)
export WIDTH="$(( MON_WIDTH / 5 ))"

( 
	echo "%{c}$@"
	sleep "$SLEEP" 
) | mybar "$(( MON_WIDTH / 2 - WIDTH / 2))" "notify" &
