#!/bin/sh

most_urgent_task() {
	id=$(task next limit:1 | tail -n +4 | head -n 1 | sed 's/^ //' | cut -d ' ' -f1)
	echo \[${id} - $(task _get ${id}.project)\] : $(task _get ${id}.description)
}

case $1 in
	wifi) nmcli dev status | grep -e 'wifi\s*connected' | column -t -o',' | cut -d',' -f4 | notify ;;
	tt)   tt | notify ;;
	task) most_urgent_task | notify ;;
esac
