#!/bin/sh

newmail() {
	echo "$MAIL/new/$(ls -t "$MAIL/new" | head -n1)"
}

grepsubj() {
	echo "$(sed 's/^Subject:\ \(.*\)$/\1/p;d' $(newmail))"
}

grepsender() {
	echo "$(sed 's/^From:.*<\(.*\)@.*$/\1/p;d' $(newmail))"
}

test -z "$(ls "$MAIL/new")" && notify "No new mail" && exit 1
notify "New mail by \"$(grepsender)\" : \"$(grepsubj)\""
