#!/bin/sh

newmail() {
	echo "$MAIL/new/$(ls -t "$MAIL/new" | head -n1)"
}

grepsender() {
	LINE=`grep -n "^From:" $(newmail)`
	LINENR=`cut -d: -f1 <<< $LINE`

	while [ -z "$NAME" ]; do
		NAME=`sed "${LINENR}s/^.*<\(.*\)@.*$/\1/p;d" $(newmail)`
		LINENR=$(( LINENR + 1))
	done
	echo $NAME
}

test -z "$(ls "$MAIL/new")" && notify "No new mail" && exit 1
SLEEP=2 notify "New mail by \"$(grepsender)\""
