#!/bin/sh

usage() {
	echo "Usage: $(basename $0) <file>" > /dev/stderr
	exit 1
}

open() {
	case "$1" in
		*md|*c|*py|*txt)
			vim "$1" ;;
		*png|*PNG|*jpg|*jpeg|*JPG)
			meh "$1" ;;
		*pdf|*PDF)
			evince "$1" ;;
		*mp4|*mkv|*mpv|*MTS|*mts|*MPG)
			mpv "$1" ;;
		*docx|*xlsx|*pptx)
			libreoffice "$1" ;;
		*)
			echo "Fallback to xdg-open" > /dev/stderr
			xdg-open "$1" > /dev/null
	esac
}

test "$1" == "-h" && usage

FILE="${1:-$(</dev/stdin)}"
open "$FILE" > /dev/null 2>&1 &
