#!/bin/sh

usage() {
	echo "Usage: $(basename $0) <file>" > /dev/stderr
	exit 1
}


open() {
	lowercase="$(echo $1 | tr [A-Z] [a-z])"
	case "$lowercase" in
		*html|*htm)
			firefox "$1" ;;
		*md|*c|*py|*txt)
			vim "$1" ;;
		*png|*jpg|*jpeg|*heic)
			feh "$1" ;;
		*pdf)
			zathura "$1" ;;
		*mp4|*mkv|*mpv|*mts|*mpg)
			mpv "$1" ;;
		*docm|*docx|*xls|*ppt|*xlsx|*pptx)
			libreoffice "$1" ;;
		*) xdg-open "$1" ;;
	esac
}

test "$1" == "-h" && usage

FILE="${1:-$(</dev/stdin)}"
open "$FILE" > /dev/null 2>&1 &
