#!/bin/sh

usage() {
	echo "Usage: $(basename $0) <file>" > /dev/stderr
	exit 1
}


open() {
	lowercase="$(echo $1 | tr [A-Z] [a-z])"
	case "$lowercase" in
		*md|*c|*py|*txt)
			vim "$1" ;;
		*png|*jpg|*jpeg|*heic)
			meh "$1" ;;
		*pdf)
			evince "$1" ;;
		*mp4|*mkv|*mpv|*mts|*mpg)
			mpv "$1" ;;
		*docx|*xlsx|*pptx|*doc|*xls|*ppt)
			libreoffice "$1" ;;
		*)
			echo "Fallback to xdg-open" > /dev/stderr
			xdg-open "$1" > /dev/null
	esac
}

test "$1" == "-h" && usage

FILE="${1:-$(</dev/stdin)}"
open "$FILE" > /dev/null 2>&1 &
