#!/bin/sh

NAME=main
MAKEFILE_TEMPLATE=$HOME/src/makefiles/latex

test ! -f $MAKEFILE_TEMPLATE && echo 'No latex template found' && exit 1

usage() {
	echo "Usage: $(basename $0) [-n document-name] <zip-file>"
	exit 1
}


while getopts "n:" opt; do
    case $opt in
        n) NAME=$OPTARG ;;
    esac
done

shift $((OPTIND - 1))

test ! -f "$1" && usage

dir="${1%.*}"

unzip -d "$dir" "$1"
cd "$dir"

cp $MAKEFILE_TEMPLATE Makefile
sed -i "s/filename/$NAME/" Makefile

