#!/bin/sh

DIR=unzipped
NAME=paper
MAKEFILE_TEMPLATE=$HOME/src/makefiles/latex

test ! -f $MAKEFILE_TEMPLATE && echo 'No latex template found' && exit 1

usage() {
	echo "Usage: $(basename $0) [-n document-name] <zip-file>"
	exit 1
}


while getopts "n:" opt; do
    case $opt in
        n) NAME=$OPTARG ;;
    esac
done

shift $((OPTIND - 1))

test ! -f "$1" && usage

unzip -d $DIR "$1"
cd $DIR

cp $MAKEFILE_TEMPLATE Makefile
sed -i "s/filename/$NAME/" Makefile

