#!/bin/bash
# based on https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu
# modified by: randomn4me

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | menu "-q -p $(basename $0)")

[[ -n $password ]] || exit

pass show -c "$password" 2>/dev/null
