#!/bin/bash

usage() {
    echo "Usage : $(basename $0) <frompage> <topage> <file> [tofile]"
}


test $# -ne 4 && usage && exit 0

gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dFirstPage="$1" -dLastPage="$2" -sOutputFile=${4:-"pdfextr_output.pdf"} "$3" 2>&1 &
