#!/bin/sh

PHOTODIR=~/usr/pics/photos

usage() {
    cat << EOF
Usage: $(basename $0) [hd] <dir>
    r: run the sorting - default is dummy run to check what will happen
    h: help
EOF
    exit 1
}

err() {
    echo "$@" > /dev/stderr
}

date_by_file() {
    DATE=$(file "$1" | grep -o '[0-9]\{4\}:[0-9]\{2\}')
}

# date_by_name() {
#     case $(echo "$1" | grep -o '[A-Za-z]' | head -n1) in
#         IMG) grep -o '[0-9]\{6\}' | head -n1 | sed 's/.\{4\}/&:/' ;;
#         signal) usage ;;
#     esac
# }

sorting() {
    for f in $(ls "$DIR"); do
        date_by_file "$f"
        [ -z $DATE ] && err "not sorted: $f" && continue

        YEAR=$(echo $DATE | cut -d: -f1)
        MONTH=$(echo $DATE | cut -d: -f2)

        NEWDIR="$PHOTODIR"/${YEAR}_${MONTH}
        if [ $RUN ]; then
            mkdir "$NEWDIR" > /dev/null 2>&1
            mv "$f" "$NEWDIR" && echo "moved $f to $NEWDIR"
        else
            [ ! -d $NEWDIR ] && echo "creating $NEWDIR"
            echo "moving $f to $NEWDIR"
        fi
    done
}

while getopts "hr" OPT; do
    case  $OPT in
        h) usage ;;
        r) RUN=true ;;
    esac
done

shift $((OPTIND - 1))

[ ! -d "$1" ] && usage || DIR="$1"

sorting
