#!/bin/bash

source $HOME/.cache/wal/colors.sh

usage() {
	cat << EOF
Usage: $(basename $0) [0|1|r|t]
EOF
}

s() {
	test -n "$(pgrep rainbow)" && printf "%s\n" "Already running" && exit 1
	rainbow "$(csq ${color3:1} ${color0:1} 10)" &
	notify "pulse on"
}

e() {
	test -z "$(pgrep rainbow)" && printf "%s\n" "Not running" && exit 1
	pkill rainbow
	bspc config active_border_color "$color3"
	notify "pulse off"
}

t() {
	test -z "$(pgrep rainbow)" && s && exit 0
	test -n "$(pgrep rainbow)" && e && exit 0
}

case $1 in
	0) e ;;
	1) s ;;
	r) e; s ;;
	t) t ;;
	*) usage ;;
esac

