#!/bin/sh

PID_FILE=$HOME/tmp/.radio
RADIO_FILE=$HOME/.radio

usage() {
	echo "Usage: $(basename $0) [-hl] <station>"
	echo ""
	echo "stations: dfl nova kultur"
	exit 1
}


start() {
	mpv --quiet $URL > /dev/null 2>&1 &
	echo $! > $PID_FILE

	echo $URL > $RADIO_FILE
}


off() {
	kill `cat $PID_FILE`
	rm $PID_FILE
}


CMD=`echo $1 | tr '[:upper:]' '[:lower:]'`

case $CMD in
	dlf)    URL='https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3' ;;
	kultur) URL='https://st02.sslstream.dlf.de/dlf/02/128/mp3/stream.mp3' ;;
	nova)   URL='https://st03.sslstream.dlf.de/dlf/03/128/mp3/stream.mp3' ;;
	0)      test -f $PID_FILE && off && exit 1;;
	-h)     usage ;;
	*)      test ! -f $RADIO_FILE && exit
	        URL="`cat $RADIO_FILE`" ;;
esac

test -f $PID_FILE && off
start
