#!/bin/sh

DIR=$HOME/.wine/drive_c/Program\ Files\ \(x86\)/StarCraft\ II

cd "$DIR"

test -x "StarCraft II.exe" || \
    ( echo "File not existing or not executable." && exit 1 )

wine start "StarCraft II.exe" > /dev/null 2>&1
