#!/bin/sh

device='airscan:w1:Brother MFC-J625DW'
tmpdir="$(mktemp -d)"
tmpscan="$tmpdir/scan"
outdir="$HOME/var/scans"

usage() {
	echo "Usage: $(basename $0) [-h]"
	exit 1
}

test "$1" = "-h" && usage

mkdir -p $outdir
name_sanitized="$(echo $@ | tr [A-Z\ ] [a-z\-])"
outfile="$outdir/$(date +%F_%Hh%Mm%Ss).pdf"

( scanimage -d "$device" -o "$tmpscan.png" && \
	convert "$tmpscan.png" "$outfile" && \
	rm -rf $tmpdir ) > /dev/null & disown

