#!/bin/sh

TMPDIR="$(mktemp -d)"
DIR="$HOME/usr/vids/screencasts"
DATE=`date '+%F_%H-%M'`

RM=$(lsw -r)
MW=$(wattr w $RM)
MH=$(wattr h $RM)

ffmpeg -f x11grab \
    -r 25 \
    -s ${MW}x${MH} \
    -loglevel quiet \
    -i :0.0 \
    -vcodec libx264 \
    -preset ultrafast \
    -threads 0 \
    -y "$TMPDIR/$DATE.mkv"

ffmpeg -i "$TMPDIR/$DATE.mkv" -c copy "$DIR/$DATE.mp4"
rm -rf $TMPDIR
