#!/bin/bash

usage() {
	cat << EOF
Usage: $(basename $0) [-h] [-u <url>] [-f <file>]
EOF
}

URL="https://0x0.st"

case $1 in
	-h|--help)  usage ;;
	-u|--url)   curl -F"shorten=$2" $URL ;;
	-f|--file)  curl -F"file=@$2" $URL ;;
	*)          usage ;;
esac
