#!/bin/bash

res=$(printf "logout\nreboot\nshutdown" | menu "-p $(basename $0)")

case "$res" in
    "logout")   ownlogout ;;
    "reboot")   systemctl reboot ;;
    "shutdown") systemctl poweroff ;;
esac

exit 0
