#!/bin/bash

res=$(echo -e "logout\nreboot\nshutdown\nsuspend" | menu)

case "$res" in
	"logout")		ownlogout ;;
	"reboot")		systemctl reboot ;;
	"shutdown")	systemctl poweroff ;;
	"suspend")	systemctl suspend ;;
esac

exit 0
