#!/bin/bash

usage() {
    cat << EOF
Usage : $(basename $0)
EOF
}

HOST="https://www.tagesschau.de"
LONG="$HOST/sendung/tagesschau/index.html"
SHORT="$HOST/100sekunden/index.html"

grepdate() {
    curl -s "$LONG" | grep og:title | sed -E "s/^.*\ ([0-9]{2}\.[0-9]{2}\.[0-9]{4}).*$/\1/p;d"
}

startvid() {
    RESPONSE="Y"

    read -n 1 -p "Date $(grepdate) correct? " RESPONSE

    case "$RESPONSE" in
        [nN])   echo ;;
        *)      mpv "$1" > /dev/null 2>&1 & ;;
    esac
}

test -z "$(ssid)" && printf "%s\n" "No network" > /dev/stderr && exit 1

case $1 in
    s|-s)   startvid $SHORT ;;
     *)     startvid $LONG ;;
esac

