#!/bin/bash

test $# -gt 0 && echo "$(usage)"

URL="https://www.tagesschau.de/sendung/tagesschau/index.html"
RESPONSE="Y"

usage() {
	cat << EOF
Usage : $(basename $0)
EOF
}
grepdate() {
	curl -s "$URL" | grep og:title | sed -E "s/^.*\ ([0-9]{2}\.[0-9]{2}\.[0-9]{4}).*$/\1/p;d"
}

read -n 1 -p "Date $(grepdate) correct? " RESPONSE

case "$RESPONSE" in
	[nN])   echo ;;
	*)      mpv "$URL" > /dev/null 2>&1 & ;;
esac

