#!/bin/sh

usage() {
	echo "Usage: $(basename $0) <c>"
}

case "$1" in
	c*) SESSION_NAME="coding" ;;
	 *) usage ;;
esac

if ! tmux has-session -t $SESSION_NAME 2> /dev/null ; then
	case $SESSION_NAME in
		coding)
			tmux new-session -d -n "c" -s $SESSION_NAME
			tmux split-window -v -p 20 -t $SESSION_NAME
			tmux select-pane -U -t $SESSION_NAME
			;;
	esac
fi

tmux attach-session -t $SESSION_NAME
