#!/bin/bash
FILE="$HOME/.todo"

usage() {
    echo "Usage: $(basename $0) [-hsn] [-a todo] [-d <line-nr>]"
    exit 1
}

add() {
    test $# -eq 0 && usage
    echo "$@" | tee -a $FILE 1> /dev/null
}

delete() {
    test $# -eq 0 && usage
    for l in "$@"; do
        echo "todo \'$(sed ${l}q $FILE)\' deleted."
        sed -i "${l}d" $FILE
    done
}

number() {
    <$FILE wc -l
}

show() {
    <$FILE nl
}

main() {
    opt=$1
    shift 1
    case "$opt" in
        -n) number ;;
        -s) show ;;
      -h|?) usage ;;
        -a) add "$@" ;;
        -d) delete "$@" ;;
         *) show
    esac
}

main "$@"
