#!/bin/bash
FILE="$HOME/.todo"

usage() {
    echo "Usage: $(basename $0) [-hsn] [-a todo] [-d <line-nr>]"
    exit 1
}

add() {
    test -n "$1" || usage
    echo "$1" | tee -a $FILE 1> /dev/null
}

delete() {
    test -n "$1" || usage
    echo "todo `sed $1q $FILE` deleted."
    sed -i "$1d" $FILE
}

number() {
    <$FILE wc -l
}

show() {
    <$FILE nl
}

main() {
    case "$1" in
        -n) number ;;
        -s) show ;;
      -h|?) usage ;;
        -a) add "$2" ;;
        -d) delete "$2" ;;
         *) show
    esac
}

main "$@"
