#!/bin/bash
FILE="${HOME}/.todo"

usage() {
	echo "Usage: $(basename $0) [-shn] [-a todo] [-d line-nr]"
	exit 0
}

add() {
	echo "$1" >> "${FILE}"
	echo "todo added"
	exit 0
}

delete() {
	test -n "$1" || exit 1
	sed -i "$1d" ${FILE}
	echo "todo deleted"
	exit 0
}

number() {
	cat "$FILE" | wc -l && exit 0
}

show() {
	echo ""
	echo -e "       ██                 ██         "
	echo -e "      ░██                ░██         "
	echo -e "     ██████  ██████      ░██  ██████ "
	echo -e "    ░░░██░  ██░░░░██  ██████ ██░░░░██"
	echo -e "      ░██  ░██   ░██ ██░░░██░██   ░██"
	echo -e "      ░██  ░██   ░██░██  ░██░██   ░██"
	echo -e "      ░░██ ░░██████ ░░██████░░██████ "
	echo -e "       ░░   ░░░░░░   ░░░░░░  ░░░░░░  "
	echo ""
	echo -e "     ████████████████████████████████"
  echo    "    ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ "
	echo ""
	test -f "${FILE}" && nl "${FILE}"
	echo ""
	exit 0
}

main() {
	while getopts "nsha:d:" opt; do
		case "$opt" in
			"n")	number ;;
			"s")	show ;;
			"h")	usage ;;
			"a")	add "$OPTARG" ;;
			"d")	delete "$OPTARG" ;;
			"?")	usage ;;
		esac
	done
	show
}

main "$@"
