#!/bin/bash

DEVICE="$(xinput list --name-only | grep -E "[Tt]ouch[Pp]ad")"

usage() {
    cat << EOF
Usage: $(basename $0) <0|1|t>
EOF
}

deven() {
    xinput enable "$DEVICE"
}

devdis() {
    xinput disable "$DEVICE"
}

toggle() {
    STATE="$(xinput list-props "$DEVICE" | grep "Device Enabled" | \
        cut -d":" -f2 | grep -oE [01])"

    if [ "$STATE" = "0" ]; then
        deven
    else
        devdis
    fi
}

test -z $# && usage && exit 1

case "$1" in
    "on"|"1")       deven ;;
    "off"|"0")      devdis ;;
    "t"|"toggle")   toggle ;;
    *)              usage ;;
esac

