#!/usr/bin/python

import datetime
import csv
import os
import sys

TMP_FILE = os.path.join(os.getenv('HOME'), 'tmp', '.timetracker')
TODAY = datetime.date.today()
BASE_DIR = os.path.join(os.getenv('HOME'), 'var', 'nextcloud', 'misc', 'timetracker')
STRF_STRING = '%H:%M'


def err(msg: str):
    print(f'[!] {msg}')
    exit(1)


def setup():
    dir = os.path.join(BASE_DIR, TODAY.strftime('%Y-%m'))

    if not os.path.isdir(dir):
        os.makedirs(dir)


def log():
    time = datetime.datetime.now()
    with open(os.path.join(str(BASE_DIR), TODAY.strftime('%Y-%m'), str(TODAY)), 'a') as f:
        f.write(f'{time.strftime(STRF_STRING)}\n')


def usage(program: str):
    print(f"{os.path.basename(program)}: <0|1|t YYYY-MM>")
    sys.exit(1)


def read_file_seconds(filepath: str):
    with open(filepath, 'r') as f:
        content = f.read().split('\n')

    times = [datetime.datetime.strptime(line, STRF_STRING) for line in content if line]
    if not (len(times) % 2) == 0:
        times.append(datetime.datetime.strptime(datetime.datetime.now().strftime(STRF_STRING),
            STRF_STRING))

    start_end = zip(times[0::2], times[1::2])
    total = sum((end - start for (start, end) in start_end), datetime.timedelta())
    return total.total_seconds()


def is_weekday(date_str: str):
    return datetime.datetime.fromisoformat(date_str).weekday() < 5


def get_time(total_seconds: int, num_files: int):
    compared = total_seconds - num_files * 28800 # seconds to work a day (8h)
    hours = int(float(compared) / 3600)
    minutes = int(float(compared - hours * 3600) / 60)
    return f'{hours}h {minutes}m'


def start_logging():
    if os.path.isfile(TMP_FILE):
        err('already logging')
    os.mknod(TMP_FILE)
    log()


def stop_logging():
    if not os.path.isfile(TMP_FILE):
        err('not logging')
    log()
    os.remove(TMP_FILE)


def total(date_str: str):
    dir = os.path.join(BASE_DIR, date_str)
    if not os.path.isdir(dir):
        err(f'no logs for {date_str}')

    files = [f for f in os.listdir(dir) if os.path.isfile(os.path.join(dir, f))]
    seconds = sum([read_file_seconds(os.path.join(dir, days)) for days in files])

    print(get_time(seconds, sum(1 for f in files if is_weekday(f))))


if __name__ == "__main__":
    setup()

    if len(sys.argv) < 2:
        total(datetime.date.today().strftime('%Y-%m'))
    elif sys.argv[1] == "0":
        stop_logging()
    elif sys.argv[1] == "1":
        start_logging()
    elif sys.argv[1] == "t" and len(sys.argv) == 3:
        total(sys.argv[2])
    else:
        usage(sys.argv[0])
