#!/bin/sh

VIDEO_DEVICE=$(v4l2-ctl --list-devices | grep 'Dummy' -a1 | tail -n1 | xargs)
CAMERA=$(gphoto2 --auto-detect | tail -n1)

test ! -c $VIDEO_DEVICE && echo "no output device; maybe reboot" && exit 1
grep -iq "canon" <<< "$CAMERA" || ( echo "Camera not found" && exit 1 )


usage() {
	echo "Usage: $(basename $0) [h] <0|1>"
}

record() {
	gphoto2 --stdout --capture-movie | \
		ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p \
		-threads 0 -f v4l2 $VIDEO_DEVICE > /dev/null 2>&1 &
}

case $1 in
	1)	record ;;
	0)	pkill ffmpeg
		pkill gphoto2 ;;
	*)	usage ;;
esac


