#!/bin/sh

BOX=protostar
IP='192.168.56.101'

case $1 in
	start|1) vboxmanage startvm ${BOX} --type headless; sleep 20 ;;
	stop|0) vboxmanage controlvm ${BOX} poweroff soft; ssh-keygen -qR ${IP} ;;
	*) echo "Usage: $(basename $0) <0|1>" ;;
esac
