#!/bin/bash

shopt -s extglob

CHANNEL=$(amixer | sed " 1s/^.*'\(.*\)'.*/\1/p;d")

usage() {
    echo "usage : $(basename $0) [shlt-+]"
}

level() {
    amixer get "$CHANNEL" | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq
}

state() {
    amixer get "$CHANNEL" | sed -n 's/^.*\[\(o[nf]\+\)\]$/\1/p' | uniq
}

which amixer > /dev/null 2>&1 \
    || ( echo "amixer not installed" && exit 1 )

test "$#" -eq 0 && echo "$(level)" && exit 0

case "$1" in
    s)  state ;;
    h)  usage ;;
    t)  pamixer -t > /dev/null ;;
    +)  pamixer --increase 5 > /dev/null ;;
    -)  pamixer --decrease 5 > /dev/null ;;
    +([[:digit:]]) ) pamixer --set-volume $1 ;;
    *)  usage ;;
esac
