#!/bin/sh
# view new photos

DIR=$HOME/usr/pics/new

trash() {
	FILE=$1
	mv ${FILE%%.*}.* $TRASH
}

if [ -n "$1" ] && [ -d "$1" ]; then
    DIR="$1"
fi

TRASH=$DIR/trash
[ ! -d $TRASH ] && mkdir $TRASH

ls ${DIR}/*.JPG ${DIR}/*.jpg | sort | meh -list | xargs -I f mv f $TRASH
