#!/bin/sh
# view new photos

DIR=~/usr/pics/new
TRASH=$DIR/trash

if [ ! -z "$1" ] && [ -d "$1" ]; then
    DIR="$1"
fi

[ ! -d $TRASH ] && mkdir $TRASH

find ${DIR} -type f -name *.JPG | meh -list | xargs -I f mv f $TRASH
