#!/bin/bash

[ $UID -ne 0 ] && echo "Not run as root" > /dev/stderr && exit 1

PID="/run/uni-vpn.pid"
USER="$(sudo -u phil pass tu-darmstadt/tu-id)"
PASS="$(sudo -u phil pass tu-darmstadt/$USER)"

case "$1" in
	up|start|1)
		if [ -f "${PID}" ]; then
			printf "%s\n" "vpn is already connected" > /dev/stderr
			exit 1
		fi
		printf "%s\n" "${PASS}" | openconnect --background --pid-file="${PID}" --quiet vpn.hrz.tu-darmstadt.de --authgroup=campus --user="${USER}" --passwd-on-stdin 2> /dev/null
		printf "%s\n" "vpn up"
		;;
	down|stop|0)
		if [ ! -f "${PID}" ]; then
			printf "%s\n" "vpn not connected" > /dev/stderr
			exit 1
		fi
		kill -TERM $(cat ${PID})
		rm ${PID}
		printf "%s\n" "vpn disconnected"
		;;
    status|s)
        [ -f ${PID} ] && echo "Up" || echo "Down"
        ;;
	*)
		printf "%s\n" "Usage: $(basename $0) <1|0>" > /dev/stderr
		exit 1
		;;
esac
exit 0
