#!/bin/bash

PID="/run/uni-vpn.pid"
USER="$(pass tu-darmstadt/tu-id)"
PASS="$(pass tu-darmstadt/$USER)"

case "$1" in
	up|start|1)
		if [ -f "${PID}" ]; then
			printf "%s\n" "vpn is already connected" > /dev/stderr
			exit 1
		fi
		printf "%s\n" "${PASS}" | sudo openconnect --background --pid-file="${PID}" --quiet vpn.hrz.tu-darmstadt.de --authgroup=campus --user="${USER}" --passwd-on-stdin 2> /dev/null
		printf "%s\n" "vpn up"
		;;
	down|stop|0)
		if [ ! -f "${PID}" ]; then
			printf "%s\n" "vpn not connected" > /dev/stderr
			exit 1
		fi
		sudo kill -TERM $(cat ${PID})
		sudo rm ${PID}
		printf "%s\n" "vpn disconnected"
		;;
	*)
		printf "%s\n" "usage: $(basename $0) <1|0>" > /dev/stderr
		exit 1
		;;
esac
exit 0
