#!/usr/bin/env bash

source "${HOME}/.cache/wal/colors.sh"

set-bar() {
	pkill bar
	bar "$color0" "$color3" "$color8" 2> /dev/null &
}

# notify-wal() {
# 	walpath=$(cat ${HOME}/.cache/wal/wal | sed "s/\..*$//")
# 	notify "Changed theme. Using wal \"$(basename -a ${walpath})\""
# }

set-bspwm-colors() {
	bspc config focused_border_color "${color3}"
	bspc config active_border_color "${color3}"
}

refresh_pulse() {
	test -n "$(pgrep rainbow)" && pulse r
}

main() {
	set-bar
#	notify-wal
	set-bspwm-colors
	refresh_pulse
}

main > /dev/null 2>&1
