#!/bin/bash

source $COLOR_FILE

set-border-colors() {
	test -n $(pgrep "bspwm") && \
		bspc config focused_border_color "$color3" && \
		bspc config normal_border_color "$color0"
}

notify_wal() {
	FILE=$(basename `cat "$WAL_CACHE/wal"`)
	SLEEP=2 notify "Wallpaper now '${FILE%.*}'"
}

main() {
	sstart bar r 2> /dev/null
	sstart pulseborder r 2> /dev/null
	set-border-colors
	notify_wal
}

main > /dev/null 2>&1
