#!/usr/bin/env bash

source "${HOME}/.cache/wal/colors.sh"

set-border-colors() {
	test -n $(pgrep "bspwm") && \
		bspc config focused_border_color "$color3" && \
		bspc config normal_border_color "$color0"
}

refresh_pulse() {
	test -n "$(pgrep rainbow)" && pulse r
}

main() {
	sstart bar r
	set-border-colors
	refresh_pulse
}

main > /dev/null 2>&1
