#!/bin/sh

WALL_DIR="$HOME/usr/pics/wallpapers"
WALL_FILE="$HOME/.cache/wallpaper"

usage() {
	cat << EOF
Usage: $(basename $0) [wal]
EOF
}

which hsetroot > /dev/null 2>&1 || \
	(printf "No hsetroot installed\n" && exit 1)

test -z $1 && hsetroot -fill `cat $WALL_FILE` && exit 0

set_wp() {
	FULL_LINK=`readlink -f "$1"`
	hsetroot -fill "$FULL_LINK"
	echo $FULL_LINK > $WALL_FILE
}

test -f $1 && set_wp "$1"
