#!/bin/sh

usage() {
    echo "Usage: $(basename $0) <wid>"
    exit 1
}

winname() {
    xprop -id "$wid" WM_CLASS | cut -d\" -f 2
}

winclass() {
    xprop -id "$wid" WM_CLASS | cut -d\" -f 4
}

test $# -eq 1 || usage
wattr $1 && wid=$1

case "$(winname)" in
    urxvt*)     snap c $wid ;;
    mupdf)      snap c $wid ;;
    *)
        case "$(winclass)" in
            mpv)        snap c $wid ;;
            Firefox)    snap tl $wid ;;
        esac
        ;;
esac
